# Generated by Django 4.2.29 on 2026-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_experience_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
