# Generated by Django 4.2.29 on 2026-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_project_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="supportiveLink",
            field=models.URLField(blank=True),
        ),
    ]
